#ifndef HAWKSERVERCORE_GLOBAL_H
#define HAWKSERVERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HAWKSERVERCORE_LIBRARY)
#  define HAWKSERVERCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define HAWKSERVERCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HAWKSERVERCORE_GLOBAL_H
